version: 1
force:
  major: 1
  existing: true
  strict: false
blacklist:
  - "Merge branch"
  - "Merge pull request"
  - "feature/"
  - "feature:"
tag_prefixes:
  # Note: "v" prefix is stripped automatically, no need to include it here
  - "app-"
  - "infra-"
wording:
  patch:
    - update
    - initial
    - fix
  minor:
    - change
    - improve
  major:
    - breaking
  release:
    - release-candidate
